apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app:1.0.0-25
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app:1.0.0-25
  template:
    metadata:
      labels:
        app: register-app:1.0.0-25
    spec:
      containers:
        - name: register-app:1.0.0-25
          image: puvisha007/register-app:1.0.0-25
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
